export const AUTH_REGISTER_REQUEST = "AUTH_REGISTER_REQUEST";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_ERROR = "AUTH_REGISTER_ERROR";

export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_ERROR = "AUTH_LOGIN_ERROR";

export const AUTH_LOAD_USER_REQUEST = "AUTH_LOAD_USER_REQUEST";
export const AUTH_LOAD_USER_SUCCESS = "AUTH_LOAD_USER_SUCCESS";
export const AUTH_LOAD_USER_ERROR = "AUTH_LOAD_USER_ERROR";