export const PROFILE_USER_PROFILE_REQUEST = "PROFILE_USER_PROFILE_REQUEST";
export const PROFILE_USER_PROFILE_SUCCESS = "PROFILE_USER_PROFILE_SUCCESS";
export const PROFILE_USER_PROFILE_ERROR = "PROFILE_USER_PROFILE_ERROR";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_ERROR = "PROFILE_CREATE_ERROR";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

export const PROFILE_DELETE_EDUCATION = "PROFILE_DELETE_EDUCATION";
export const PROFILE_DELETE_EXPERIENCE = "PROFILE_DELETE_EXPERIENCE";