export const PROFILE_USER_REQUEST = "PROFILE_USER_REQUEST";
export const PROFILE_USER_SUCCESS = "PROFILE_USER_SUCCESS";
export const PROFILE_USER_ERROR = "PROFILE_USER_ERROR";

export const PROFILE_CLEAR_USER = "PROFILE_CLEAR_USER";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_ERROR = "PROFILE_CREATE_ERROR";

export const PROFILE_ADD_EDUCATION = "PROFILE_ADD_EDUCATION";

export const PROFILE_ADD_EXPERIENCE = "PROFILE_ADD_EXPERIENCE";

export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_ERROR = "PROFILE_LIST_ERROR";

export const PROFILE_USER_ID_REQUEST = "PROFILE_USER_ID_REQUEST";
export const PROFILE_USER_ID_SUCCESS = "PROFILE_USER_ID_SUCCESS";
export const PROFILE_USER_ID_ERROR = "PROFILE_USER_ID_ERROR";

export const PROFILE_USER_ID_CLEAR = "PROFILE_USER_ID_CLEAR";

export const PROFILE_REPOS_REQUEST = "PROFILE_REPOS_REQUEST";
export const PROFILE_REPOS_SUCCESS = "PROFILE_REPOS_SUCCESS";
export const PROFILE_REPOS_ERROR = "PROFILE_REPOS_ERROR";
