export const PROFILE_USER_PROFILE_REQUEST = "PROFILE_USER_PROFILE_REQUEST";
export const PROFILE_USER_PROFILE_SUCCESS = "PROFILE_USER_PROFILE_SUCCESS";
export const PROFILE_USER_PROFILE_ERROR = "PROFILE_USER_PROFILE_ERROR";

export const PROFILE_CREATE_REQUEST = "PROFILE_CREATE_REQUEST";
export const PROFILE_CREATE_SUCCESS = "PROFILE_CREATE_SUCCESS";
export const PROFILE_CREATE_ERROR = "PROFILE_CREATE_ERROR";

export const PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

export const PROFILE_DELETE_EXP_REQUEST = "PROFILE_DELETE_EXP_REQUEST";
export const PROFILE_DELETE_EXP_SUCCESS = "PROFILE_DELETE_EXP_SUCCESS";
export const PROFILE_DELETE_EXP_ERROR = "PROFILE_DELETE_EXP_ERROR";

export const PROFILE_DELETE_EDU_REQUEST = "PROFILE_DELETE_EDU_REQUEST";
export const PROFILE_DELETE_EDU_SUCCESS = "PROFILE_DELETE_EDU_SUCCESS";
export const PROFILE_DELETE_EDU_ERROR = "PROFILE_DELETE_EDU_ERROR";

export const PROFILE_LIST_REQUEST = "PROFILE_LIST_REQUEST";
export const PROFILE_LIST_SUCCESS = "PROFILE_LIST_SUCCESS";
export const PROFILE_LIST_ERROR = "PROFILE_LIST_ERROR";

export const PROFILE_BY_ID_REQUEST = "PROFILE_BY_ID_REQUEST";
export const PROFILE_BY_ID_SUCCESS = "PROFILE_BY_ID_SUCCESS";
export const PROFILE_BY_ID_ERROR = "PROFILE_BY_ID_ERROR";

export const PROFILE_GITHUB_REPOS_REQUEST = "PROFILE_GITHUB_REPOS_REQUEST";
export const PROFILE_GITHUB_REPOS_SUCCESS = "PROFILE_GITHUB_REPOS_SUCCESS";
export const PROFILE_GITHUB_REPOS_ERROR = "PROFILE_GITHUB_REPOS_ERROR";

export const PROFILE_CLEAR_REPOS = "PROFILE_CLEAR_REPOS";